/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package simpleloginform;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.sql.Statement;
import java.awt.Color;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author SHAMS
 */
public class seatPlan extends javax.swing.JFrame {

    String time;
    String timeStr = time;
    mainPanel m = new mainPanel();
    String dateStr = mainPanel.d;
    String fromStr = mainPanel.fromD;
    String toStr = mainPanel.toD;

    /**
     * Creates new form seatPlan
     */
    public seatPlan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        passenger = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        A1 = new javax.swing.JButton();
        A2 = new javax.swing.JButton();
        A3 = new javax.swing.JButton();
        A4 = new javax.swing.JButton();
        A5 = new javax.swing.JButton();
        A6 = new javax.swing.JButton();
        A7 = new javax.swing.JButton();
        A8 = new javax.swing.JButton();
        A9 = new javax.swing.JButton();
        A10 = new javax.swing.JButton();
        A11 = new javax.swing.JButton();
        A12 = new javax.swing.JButton();
        A13 = new javax.swing.JButton();
        A14 = new javax.swing.JButton();
        A15 = new javax.swing.JButton();
        A16 = new javax.swing.JButton();
        A17 = new javax.swing.JButton();
        A18 = new javax.swing.JButton();
        A19 = new javax.swing.JButton();
        A20 = new javax.swing.JButton();
        A21 = new javax.swing.JButton();
        A22 = new javax.swing.JButton();
        A23 = new javax.swing.JButton();
        A24 = new javax.swing.JButton();
        A25 = new javax.swing.JButton();
        A26 = new javax.swing.JButton();
        A27 = new javax.swing.JButton();
        A28 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        timeBUS = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));

        passenger.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        passenger.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        passenger.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        passenger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passengerActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(153, 0, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        A1.setText("A1");
        A1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A1MouseClicked(evt);
            }
        });
        A1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A1ActionPerformed(evt);
            }
        });

        A2.setText("A2");
        A2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A2MouseClicked(evt);
            }
        });
        A2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A2ActionPerformed(evt);
            }
        });

        A3.setText("A3");
        A3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A3MouseClicked(evt);
            }
        });

        A4.setText("A4");
        A4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A4ActionPerformed(evt);
            }
        });

        A5.setText("B1");
        A5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A5ActionPerformed(evt);
            }
        });

        A6.setText("B2");
        A6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A6ActionPerformed(evt);
            }
        });

        A7.setText("B3");
        A7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A7ActionPerformed(evt);
            }
        });

        A8.setText("B4");
        A8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A8ActionPerformed(evt);
            }
        });

        A9.setText("C1");
        A9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A9ActionPerformed(evt);
            }
        });

        A10.setText("C2");
        A10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A10ActionPerformed(evt);
            }
        });

        A11.setText("C3");
        A11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A11ActionPerformed(evt);
            }
        });

        A12.setText("C4");
        A12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A12ActionPerformed(evt);
            }
        });

        A13.setText("D1");
        A13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A13ActionPerformed(evt);
            }
        });

        A14.setText("D2");
        A14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A14ActionPerformed(evt);
            }
        });

        A15.setText("D3");
        A15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A15ActionPerformed(evt);
            }
        });

        A16.setText("D4");
        A16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A16ActionPerformed(evt);
            }
        });

        A17.setText("E1");
        A17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A17ActionPerformed(evt);
            }
        });

        A18.setText("E2");
        A18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A18ActionPerformed(evt);
            }
        });

        A19.setText("E3");
        A19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A19ActionPerformed(evt);
            }
        });

        A20.setText("E4");
        A20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A20ActionPerformed(evt);
            }
        });

        A21.setText("F1");
        A21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A21ActionPerformed(evt);
            }
        });

        A22.setText("F2");
        A22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A22ActionPerformed(evt);
            }
        });

        A23.setText("F3");
        A23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A23ActionPerformed(evt);
            }
        });

        A24.setText("F4");
        A24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A24ActionPerformed(evt);
            }
        });

        A25.setText("G1");
        A25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A25ActionPerformed(evt);
            }
        });

        A26.setText("G2");
        A26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A26ActionPerformed(evt);
            }
        });

        A27.setText("G3");
        A27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A27ActionPerformed(evt);
            }
        });

        A28.setText("G4");
        A28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A28ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(102, 51, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setText("Get Ticket");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(A25, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A26, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                        .addComponent(A27, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(A21, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A22, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(A23, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(A17, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A18, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(A19, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(A13, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A14, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(A15, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(A9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A10, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(A11, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(A5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(A7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(A1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(A3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(A4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(A8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(A12, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(A16, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(A20, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(A24, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(A28, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(97, 97, 97))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(A1)
                    .addComponent(A2)
                    .addComponent(A3)
                    .addComponent(A4))
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(A5)
                    .addComponent(A6)
                    .addComponent(A7)
                    .addComponent(A8))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(A9)
                    .addComponent(A10)
                    .addComponent(A11)
                    .addComponent(A12))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(A13)
                    .addComponent(A14)
                    .addComponent(A15)
                    .addComponent(A16))
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(A17)
                    .addComponent(A18)
                    .addComponent(A19)
                    .addComponent(A20))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(A21)
                    .addComponent(A22)
                    .addComponent(A23)
                    .addComponent(A24))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(A25)
                    .addComponent(A26)
                    .addComponent(A27)
                    .addComponent(A28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(33, 33, 33))
        );

        timeBUS.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        timeBUS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "7.00 AM", "9.00 AM", "11.00 AM", "2.00 PM", "4.00 PM", "6.00 PM", "11.00 PM" }));
        timeBUS.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        timeBUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeBUSActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Time");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Number of Passenger");

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Show");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Available Seat");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("After select your seat press the \"Get Ticket\" Button");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(passenger, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addComponent(timeBUS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 357, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(passenger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(timeBUS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int k = 0, cnt = 1, a1 = 1, a2 = 1, a3 = 1, a4 = 1;
    int a5 = 1, a6 = 1, a7 = 1, a8 = 1;
    int a9 = 1, a10 = 1, a11 = 1, a12 = 1;
    int a13 = 1, a14 = 1, a15 = 1, a16 = 1;
    int a17 = 1, a18 = 1, a19 = 1, a20 = 1;
    int a21 = 1, a22 = 1, a23 = 1, a24 = 1;
    int a25 = 1, a26 = 1, a27 = 1, a28 = 1;
    String selectSeat = "";
    private void passengerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passengerActionPerformed
        // TODO add your handling code here:
        k = 0;
        cnt = Integer.valueOf((String) passenger.getSelectedItem());
        A1.setBackground(new Color(240, 240, 240).brighter());
        A2.setBackground(new Color(240, 240, 240).brighter());
        A3.setBackground(new Color(240, 240, 240).brighter());
        A4.setBackground(new Color(240, 240, 240).brighter());
        A5.setBackground(new Color(240, 240, 240).brighter());
        A6.setBackground(new Color(240, 240, 240).brighter());
        A7.setBackground(new Color(240, 240, 240).brighter());
        A8.setBackground(new Color(240, 240, 240).brighter());
        A9.setBackground(new Color(240, 240, 240).brighter());
        A10.setBackground(new Color(240, 240, 240).brighter());
        A11.setBackground(new Color(240, 240, 240).brighter());
        A12.setBackground(new Color(240, 240, 240).brighter());
        A13.setBackground(new Color(240, 240, 240).brighter());
        A14.setBackground(new Color(240, 240, 240).brighter());
        A15.setBackground(new Color(240, 240, 240).brighter());
        A16.setBackground(new Color(240, 240, 240).brighter());
        A17.setBackground(new Color(240, 240, 240).brighter());
        A18.setBackground(new Color(240, 240, 240).brighter());
        A19.setBackground(new Color(240, 240, 240).brighter());
        A20.setBackground(new Color(240, 240, 240).brighter());
        A21.setBackground(new Color(240, 240, 240).brighter());
        A22.setBackground(new Color(240, 240, 240).brighter());
        A23.setBackground(new Color(240, 240, 240).brighter());
        A24.setBackground(new Color(240, 240, 240).brighter());
        A25.setBackground(new Color(240, 240, 240).brighter());
        A26.setBackground(new Color(240, 240, 240).brighter());
        A27.setBackground(new Color(240, 240, 240).brighter());
        A28.setBackground(new Color(240, 240, 240).brighter());
        selecteda1 = 0;
        selecteda2 = 0;
        selecteda3 = 0;
        selecteda4 = 0;
        selecteda5 = 0;
        selecteda6 = 0;
        selecteda7 = 0;
        selecteda8 = 0;
        selecteda9 = 0;
        selecteda10 = 0;
        selecteda11 = 0;
        selecteda12 = 0;
        selecteda13 = 0;
        selecteda14 = 0;
        selecteda15 = 0;
        selecteda16 = 0;
        selecteda17 = 0;
        selecteda18 = 0;
        selecteda19 = 0;
        selecteda20 = 0;
        selecteda21 = 0;
        selecteda22 = 0;
        selecteda23 = 0;
        selecteda24 = 0;
        selecteda25 = 0;
        selecteda26 = 0;
        selecteda27 = 0;
        selecteda28 = 0;
        a1 = 1;
        a2 = 1;
        a3 = 1;
        a4 = 1;
        a5 = 1;
        a6 = 1;
        a7 = 1;
        a8 = 1;
        a9 = 1;
        a10 = 1;
        a11 = 1;
        a12 = 1;
        a13 = 1;
        a14 = 1;
        a15 = 1;
        a16 = 1;
        a17 = 1;
        a18 = 1;
        a19 = 1;
        a20 = 1;
        a21 = 1;
        a22 = 1;
        a23 = 1;
        a24 = 1;
        a25 = 1;
        a26 = 1;
        a27 = 1;
        a28 = 1;
        //JOptionPane.showMessageDialog(null,cnt);
    }//GEN-LAST:event_passengerActionPerformed

    private void A1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A1ActionPerformed

    private void A2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A2ActionPerformed

    int selecteda1 = 0;
    private void A1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A1MouseClicked
        // TODO add your handling code here:
        if (a1 % 2 == 1 && k < cnt) {
            A1.setBackground(new Color(3, 59, 90).brighter());
            k = k + 1;
            selecteda1 = 1;
            //JOptionPane.showMessageDialog(null,"Login Successful");
        } else {
            A1.setBackground(new Color(240, 240, 240).brighter());
            if (k > 0 && k != cnt) {
                k = k - 1;
            } else if (k > 0 && selecteda1 == 1) {
                k = k - 1;
                selecteda1 = 0;
            }
            selecteda2 = 0;
        }
        a1 = a1 + 1;
    }//GEN-LAST:event_A1MouseClicked
    int selecteda2 = 0;
    private void A2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A2MouseClicked
        // TODO add your handling code here:
        if (a2 % 2 == 1 && k < cnt) {
            A2.setBackground(new Color(3, 59, 90).brighter());
            k = k + 1;
            selecteda2 = 1;
        } else {
            A2.setBackground(new Color(240, 240, 240).brighter());
            if (k > 0 && k != cnt) {
                k = k - 1;
            } else if (k > 0 && selecteda2 == 1) {
                k = k - 1;
                selecteda2 = 0;
            }
            selecteda2 = 0;
        }
        a2 = a2 + 1;
    }//GEN-LAST:event_A2MouseClicked

    int selecteda3 = 0;
    private void A3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A3MouseClicked

        if (a3 % 2 == 1 && k < cnt) {
            A3.setBackground(new Color(3, 59, 90).brighter());
            k = k + 1;
            selecteda3 = 1;
        } else {
            A3.setBackground(new Color(240, 240, 240).brighter());
            if (k > 0 && k != cnt) {
                k = k - 1;
            } else if (k > 0 && selecteda3 == 1) {
                k = k - 1;
                selecteda3 = 0;

            }
            selecteda3 = 0;
        }
        a3 = a3 + 1;
    }//GEN-LAST:event_A3MouseClicked
    int selecteda4 = 0;
    private void A4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A4ActionPerformed
        // TODO add your handling code here:
        if (a4 % 2 == 1 && k < cnt) {
            A4.setBackground(new Color(3, 59, 90).brighter());
            k = k + 1;
            selecteda4 = 1;
        } else {
            A4.setBackground(new Color(240, 240, 240).brighter());
            if (k > 0 && k != cnt) {
                k = k - 1;
            } else if (k > 0 && selecteda4 == 1) {
                k = k - 1;
                selecteda4 = 0;
            }
            selecteda4 = 0;
        }
        a4 = a4 + 1;
    }//GEN-LAST:event_A4ActionPerformed
    int selecteda5 = 0;
    private void A5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A5ActionPerformed
        // TODO add your handling code here:
        if (a5 % 2 == 1 && k < cnt) {
            A5.setBackground(new Color(3, 59, 90).brighter());
            k = k + 1;
            selecteda5 = 1;
        } else {
            A5.setBackground(new Color(240, 240, 240).brighter());
            if (k > 0 && k != cnt) {
                k = k - 1;
            } else if (k > 0 && selecteda5 == 1) {
                k = k - 1;
                selecteda5 = 0;
            }
            selecteda5 = 0;
        }
        a5 = a5 + 1;
    }//GEN-LAST:event_A5ActionPerformed
    int selecteda6 = 0;
    private void A6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A6ActionPerformed
        // TODO add your handling code here:
        if (a6 % 2 == 1 && k < cnt) {
            A6.setBackground(new Color(3, 59, 90).brighter());
            k = k + 1;
            selecteda6 = 1;
        } else {
            A6.setBackground(new Color(240, 240, 240).brighter());
            if (k > 0 && k != cnt) {
                k = k - 1;
            } else if (k > 0 && selecteda6 == 1) {
                k = k - 1;
                selecteda6 = 0;
            }
            selecteda6 = 0;
        }
        a6 = a6 + 1;
    }//GEN-LAST:event_A6ActionPerformed
    int selecteda7 = 0;
    private void A7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A7ActionPerformed
        // TODO add your handling code here:
        if (a7 % 2 == 1 && k < cnt) {
            A7.setBackground(new Color(3, 59, 90).brighter());
            k = k + 1;
            selecteda7 = 1;
        } else {
            A7.setBackground(new Color(240, 240, 240).brighter());
            if (k > 0 && k != cnt) {
                k = k - 1;
            } else if (k > 0 && selecteda7 == 1) {
                k = k - 1;
                selecteda7 = 0;
            }
            selecteda7 = 0;
        }
        a7 = a7 + 1;
    }//GEN-LAST:event_A7ActionPerformed
    int selecteda8 = 0;
    private void A8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A8ActionPerformed
        // TODO add your handling code here:
        if (a8 % 2 == 1 && k < cnt) {
            A8.setBackground(new Color(3, 59, 90).brighter());
            k = k + 1;
            selecteda8 = 1;
        } else {
            A8.setBackground(new Color(240, 240, 240).brighter());
            if (k > 0 && k != cnt) {
                k = k - 1;
            } else if (k > 0 && selecteda8 == 1) {
                k = k - 1;
                selecteda8 = 0;
            }
            selecteda8 = 0;
        }
        a8 = a8 + 1;
    }//GEN-LAST:event_A8ActionPerformed
    int selecteda9 = 0;
    private void A9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A9ActionPerformed
        // TODO add your handling code here:
        if (a9 % 2 == 1 && k < cnt) {
            A9.setBackground(new Color(3, 59, 90).brighter());
            k = k + 1;
            selecteda9 = 1;
        } else {
            A9.setBackground(new Color(240, 240, 240).brighter());
            if (k > 0 && k != cnt) {
                k = k - 1;
            } else if (k > 0 && selecteda9 == 1) {
                k = k - 1;
                selecteda9 = 0;
            }
            selecteda9 = 0;
        }
        a9 = a9 + 1;
    }//GEN-LAST:event_A9ActionPerformed
    int selecteda10 = 0;
    private void A10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A10ActionPerformed
        // TODO add your handling code here:
        if (a10 % 2 == 1 && k < cnt) {
            A10.setBackground(new Color(3, 59, 90).brighter());
            k = k + 1;
            selecteda10 = 1;
        } else {
            A10.setBackground(new Color(240, 240, 240).brighter());
            if (k > 0 && k != cnt) {
                k = k - 1;
            } else if (k > 0 && selecteda10 == 1) {
                k = k - 1;
                selecteda10 = 0;
            }
            selecteda10 = 0;
        }
        a10 = a10 + 1;
    }//GEN-LAST:event_A10ActionPerformed
    int selecteda11 = 0;
    private void A11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A11ActionPerformed
        // TODO add your handling code here:
        if (a11 % 2 == 1 && k < cnt) {
            A11.setBackground(new Color(3, 59, 90).brighter());
            k = k + 1;
            selecteda11 = 1;
        } else {
            A11.setBackground(new Color(240, 240, 240).brighter());
            if (k > 0 && k != cnt) {
                k = k - 1;
            } else if (k > 0 && selecteda11 == 1) {
                k = k - 1;
                selecteda11 = 0;
            }
            selecteda11 = 0;
        }
        a11 = a11 + 1;
    }//GEN-LAST:event_A11ActionPerformed
    int selecteda12 = 0;
    private void A12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A12ActionPerformed
        // TODO add your handling code here:
        if (a12 % 2 == 1 && k < cnt) {
            A12.setBackground(new Color(3, 59, 90).brighter());
            k = k + 1;
            selecteda12 = 1;
        } else {
            A12.setBackground(new Color(240, 240, 240).brighter());
            if (k > 0 && k != cnt) {
                k = k - 1;
            } else if (k > 0 && selecteda12 == 1) {
                k = k - 1;
                selecteda12 = 0;
            }
            selecteda12 = 0;
        }
        a12 = a12 + 1;
    }//GEN-LAST:event_A12ActionPerformed
    int selecteda13 = 0;
    private void A13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A13ActionPerformed
        // TODO add your handling code here:
        if (a13 % 2 == 1 && k < cnt) {
            A13.setBackground(new Color(3, 59, 90).brighter());
            k = k + 1;
            selecteda13 = 1;
        } else {
            A13.setBackground(new Color(240, 240, 240).brighter());
            if (k > 0 && k != cnt) {
                k = k - 1;
            } else if (k > 0 && selecteda13 == 1) {
                k = k - 1;
                selecteda13 = 0;
            }
            selecteda13 = 0;
        }
        a13 = a13 + 1;
    }//GEN-LAST:event_A13ActionPerformed
    int selecteda14 = 0;
    private void A14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A14ActionPerformed
        // TODO add your handling code here:
        if (a14 % 2 == 1 && k < cnt) {
            A14.setBackground(new Color(3, 59, 90).brighter());
            k = k + 1;
            selecteda14 = 1;
        } else {
            A14.setBackground(new Color(240, 240, 240).brighter());
            if (k > 0 && k != cnt) {
                k = k - 1;
            } else if (k > 0 && selecteda14 == 1) {
                k = k - 1;
                selecteda14 = 0;
            }
            selecteda14 = 0;
        }
        a14 = a14 + 1;
    }//GEN-LAST:event_A14ActionPerformed
    int selecteda15 = 0;
    private void A15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A15ActionPerformed
        // TODO add your handling code here:
        if (a15 % 2 == 1 && k < cnt) {
            A15.setBackground(new Color(3, 59, 90).brighter());
            k = k + 1;
            selecteda15 = 1;
        } else {
            A15.setBackground(new Color(240, 240, 240).brighter());
            if (k > 0 && k != cnt) {
                k = k - 1;
            } else if (k > 0 && selecteda15 == 1) {
                k = k - 1;
                selecteda15 = 0;
            }
            selecteda15 = 0;
        }
        a15 = a15 + 1;
    }//GEN-LAST:event_A15ActionPerformed
    int selecteda16 = 0;
    private void A16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A16ActionPerformed
        // TODO add your handling code here:
        if (a16 % 2 == 1 && k < cnt) {
            A16.setBackground(new Color(3, 59, 90).brighter());
            k = k + 1;
            selecteda16 = 1;
        } else {
            A16.setBackground(new Color(240, 240, 240).brighter());
            if (k > 0 && k != cnt) {
                k = k - 1;
            } else if (k > 0 && selecteda16 == 1) {
                k = k - 1;
                selecteda16 = 0;
            }
            selecteda16 = 0;
        }
        a16 = a16 + 1;
    }//GEN-LAST:event_A16ActionPerformed
    int selecteda17 = 0;
    private void A17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A17ActionPerformed
        // TODO add your handling code here:
        if (a17 % 2 == 1 && k < cnt) {
            A17.setBackground(new Color(3, 59, 90).brighter());
            k = k + 1;
            selecteda17 = 1;
        } else {
            A17.setBackground(new Color(240, 240, 240).brighter());
            if (k > 0 && k != cnt) {
                k = k - 1;
            } else if (k > 0 && selecteda17 == 1) {
                k = k - 1;
                selecteda17 = 0;
            }
            selecteda17 = 0;
        }
        a17 = a17 + 1;
    }//GEN-LAST:event_A17ActionPerformed
    int selecteda18 = 0;
    private void A18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A18ActionPerformed
        // TODO add your handling code here:
        if (a18 % 2 == 1 && k < cnt) {
            A18.setBackground(new Color(3, 59, 90).brighter());
            k = k + 1;
            selecteda18 = 1;
        } else {
            A18.setBackground(new Color(240, 240, 240).brighter());
            if (k > 0 && k != cnt) {
                k = k - 1;
            } else if (k > 0 && selecteda18 == 1) {
                k = k - 1;
                selecteda18 = 0;
            }
            selecteda18 = 0;
        }
        a18 = a18 + 1;
    }//GEN-LAST:event_A18ActionPerformed
    int selecteda19 = 0;
    private void A19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A19ActionPerformed
        // TODO add your handling code here:
        if (a19 % 2 == 1 && k < cnt) {
            A19.setBackground(new Color(3, 59, 90).brighter());
            k = k + 1;
            selecteda19 = 1;
        } else {
            A19.setBackground(new Color(240, 240, 240).brighter());
            if (k > 0 && k != cnt) {
                k = k - 1;
            } else if (k > 0 && selecteda19 == 1) {
                k = k - 1;
                selecteda19 = 0;
            }
            selecteda19 = 0;
        }
        a19 = a19 + 1;
    }//GEN-LAST:event_A19ActionPerformed
    int selecteda20 = 0;
    private void A20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A20ActionPerformed
        // TODO add your handling code here:
        if (a20 % 2 == 1 && k < cnt) {
            A20.setBackground(new Color(3, 59, 90).brighter());
            k = k + 1;
            selecteda20 = 1;
        } else {
            A20.setBackground(new Color(240, 240, 240).brighter());
            if (k > 0 && k != cnt) {
                k = k - 1;
            } else if (k > 0 && selecteda20 == 1) {
                k = k - 1;
                selecteda20 = 0;
            }
            selecteda20 = 0;
        }
        a20 = a20 + 1;
    }//GEN-LAST:event_A20ActionPerformed
    int selecteda21 = 0;
    private void A21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A21ActionPerformed
        // TODO add your handling code here:
        if (a21 % 2 == 1 && k < cnt) {
            A21.setBackground(new Color(3, 59, 90).brighter());
            k = k + 1;
            selecteda21 = 1;
        } else {
            A21.setBackground(new Color(240, 240, 240).brighter());
            if (k > 0 && k != cnt) {
                k = k - 1;
            } else if (k > 0 && selecteda21 == 1) {
                k = k - 1;
                selecteda21 = 0;
            }
            selecteda21 = 0;
        }
        a21 = a21 + 1;
    }//GEN-LAST:event_A21ActionPerformed
    int selecteda22 = 0;
    private void A22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A22ActionPerformed
        // TODO add your handling code here:
        if (a22 % 2 == 1 && k < cnt) {
            A22.setBackground(new Color(3, 59, 90).brighter());
            k = k + 1;
            selecteda22 = 1;
        } else {
            A22.setBackground(new Color(240, 240, 240).brighter());
            if (k > 0 && k != cnt) {
                k = k - 1;
            } else if (k > 0 && selecteda22 == 1) {
                k = k - 1;
                selecteda22 = 0;
            }
            selecteda22 = 0;
        }
        a22 = a22 + 1;
    }//GEN-LAST:event_A22ActionPerformed
    int selecteda23 = 0;
    private void A23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A23ActionPerformed
        // TODO add your handling code here:
        if (a23 % 2 == 1 && k < cnt) {
            A23.setBackground(new Color(3, 59, 90).brighter());
            k = k + 1;
            selecteda23 = 1;
        } else {
            A23.setBackground(new Color(240, 240, 240).brighter());
            if (k > 0 && k != cnt) {
                k = k - 1;
            } else if (k > 0 && selecteda23 == 1) {
                k = k - 1;
                selecteda23 = 0;
            }
            selecteda23 = 0;
        }
        a23 = a23 + 1;
    }//GEN-LAST:event_A23ActionPerformed
    int selecteda24 = 0;
    private void A24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A24ActionPerformed
        // TODO add your handling code here:
        if (a24 % 2 == 1 && k < cnt) {
            A24.setBackground(new Color(3, 59, 90).brighter());
            k = k + 1;
            selecteda24 = 1;
        } else {
            A24.setBackground(new Color(240, 240, 240).brighter());
            if (k > 0 && k != cnt) {
                k = k - 1;
            } else if (k > 0 && selecteda24 == 1) {
                k = k - 1;
                selecteda24 = 0;
            }
            selecteda24 = 0;
        }
        a24 = a24 + 1;
    }//GEN-LAST:event_A24ActionPerformed
    int selecteda25 = 0;
    private void A25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A25ActionPerformed
        // TODO add your handling code here:
        if (a25 % 2 == 1 && k < cnt) {
            A25.setBackground(new Color(3, 59, 90).brighter());
            k = k + 1;
            selecteda25 = 1;
        } else {
            A25.setBackground(new Color(240, 240, 240).brighter());
            if (k > 0 && k != cnt) {
                k = k - 1;
            } else if (k > 0 && selecteda25 == 1) {
                k = k - 1;
                selecteda25 = 0;
            }
            selecteda25 = 0;
        }
        a25 = a25 + 1;
    }//GEN-LAST:event_A25ActionPerformed
    int selecteda26 = 0;
    private void A26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A26ActionPerformed
        // TODO add your handling code here:
        if (a26 % 2 == 1 && k < cnt) {
            A26.setBackground(new Color(3, 59, 90).brighter());
            k = k + 1;
            selecteda26 = 1;
        } else {
            A26.setBackground(new Color(240, 240, 240).brighter());
            if (k > 0 && k != cnt) {
                k = k - 1;
            } else if (k > 0 && selecteda26 == 1) {
                k = k - 1;
                selecteda26 = 0;
            }
            selecteda26 = 0;
        }
        a26 = a26 + 1;
    }//GEN-LAST:event_A26ActionPerformed
    int selecteda27 = 0;
    private void A27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A27ActionPerformed
        // TODO add your handling code here:
        if (a27 % 2 == 1 && k < cnt) {
            A27.setBackground(new Color(3, 59, 90).brighter());
            k = k + 1;
            selecteda27 = 1;
        } else {
            A27.setBackground(new Color(240, 240, 240).brighter());
            if (k > 0 && k != cnt) {
                k = k - 1;
            } else if (k > 0 && selecteda27 == 1) {
                k = k - 1;
                selecteda27 = 0;
            }
            selecteda27 = 0;
        }
        a27 = a27 + 1;
    }//GEN-LAST:event_A27ActionPerformed
    int selecteda28 = 0;
    private void A28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A28ActionPerformed
        // TODO add your handling code here:
        if (a28 % 2 == 1 && k < cnt) {
            A28.setBackground(new Color(3, 59, 90).brighter());
            k = k + 1;
            selecteda28 = 1;
        } else {
            A28.setBackground(new Color(240, 240, 240).brighter());
            if (k > 0 && k != cnt) {
                k = k - 1;
            } else if (k > 0 && selecteda28 == 1) {
                k = k - 1;
                selecteda28 = 0;
            }
            selecteda28 = 0;
        }
        a28 = a28 + 1;
    }//GEN-LAST:event_A28ActionPerformed

    private void timeBUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeBUSActionPerformed

        time = null;
        time = String.valueOf((String) timeBUS.getSelectedItem());
        //JOptionPane.showMessageDialog(null,time);
    }//GEN-LAST:event_timeBUSActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        timeStr = time;
        m = new mainPanel();
        dateStr = mainPanel.d;
        fromStr = mainPanel.fromD;
        toStr = mainPanel.toD;

        //String queryDate = "SELECT * FROM `reserve` WHERE `fromLOC` = ? AND `toLOC` = ? AND `date` = ? AND `time` = ? AND `seat` = ? ";
        try {
            Connection con = MY_CNX.getConnection();
            Statement stmt = con.createStatement();
            String query = "select * from reserve";
            ResultSet rs = stmt.executeQuery(query);

            boolean flag = false;
            String seatt = "";

            while (rs.next()) {
                //JOptionPane.showMessageDialog(null,fromStr+" "+toStr+" "+dateStr+" "+timeStr);

                String f = rs.getString("fromLOC");
                String t = rs.getString("toLOC");
                String d = rs.getString("date");
                String ti = rs.getString("time");
                seatt = rs.getString("seat");

                //JOptionPane.showMessageDialog(null,f+" "+t+" "+d+" "+ti+" "+seatt);
                if (f.equals(fromStr)) {
                    if (t.equals(toStr)) {
                        if (d.equals(dateStr)) {
                            if (ti.equals(timeStr)) {
                                flag = true;
                                JOptionPane.showMessageDialog(null, seatt);
                            }
                        }
                    }

                }

            }

            if (flag == false) {
                JOptionPane.showMessageDialog(null, "All seats are available");
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int temp = cnt;
        boolean f1 = true, f2 = true, f3 = true, f4 = true, f5 = true, f6 = true, f7 = true, f8 = true, f9 = true, f10 = true, f11 = true, f12 = true, f13 = true, f14 = true, f15 = true, f16 = true, f17 = true, f18 = true, f19 = true, f20 = true, f21 = true, f22 = true, f23 = true, f24 = true, f25 = true, f26 = true, f27 = true, f28 = true;

        while (true) {
            if (temp == 0) {
                break;
            }

            if (selecteda1 == 1 && f1 == true) {
                selectSeat = selectSeat + "A1";
                f1 = false;
            }

            if (selecteda2 == 1 && f2 == true) {
                selectSeat = selectSeat + "A2";
                f2 = false;
            }

            if (selecteda3 == 1 && f3 == true) {
                selectSeat = selectSeat + "A3";
                f3 = false;
            }

            if (selecteda4 == 1 && f4 == true) {
                selectSeat = selectSeat + "A4";
                f4 = false;
            }

            if (selecteda5 == 1 && f5 == true) {
                selectSeat = selectSeat + "B1";
                f5 = false;
            }

            if (selecteda6 == 1 && f6 == true) {
                selectSeat = selectSeat + "B2";
                f6 = false;
            }

            if (selecteda7 == 1 && f7 == true) {
                selectSeat = selectSeat + "B3";
                f7 = false;
            }

            if (selecteda8 == 1 && f8 == true) {
                selectSeat = selectSeat + "B4";
                f8 = false;
            }

            if (selecteda9 == 1 && f9 == true) {
                selectSeat = selectSeat + "C1";
                f9 = false;
            }

            if (selecteda10 == 1 && f10 == true) {
                selectSeat = selectSeat + "C2";
                f10 = false;
            }

            if (selecteda11 == 1 && f11 == true) {
                selectSeat = selectSeat + "C3";
                f11 = false;
            }

            if (selecteda12 == 1 && f12 == true) {
                selectSeat = selectSeat + "C4";
                f12 = false;
            }

            if (selecteda13 == 1 && f13 == true) {
                selectSeat = selectSeat + "D1";
                f13 = false;
            }

            if (selecteda14 == 1 && f14 == true) {
                selectSeat = selectSeat + "D2";
                f14 = false;
            }

            if (selecteda15 == 1 && f15 == true) {
                selectSeat = selectSeat + "D3";
                f15 = false;
            }

            if (selecteda16 == 1 && f16 == true) {
                selectSeat = selectSeat + "D4";
                f16 = false;
            }

            if (selecteda17 == 1 && f17 == true) {
                selectSeat = selectSeat + "E1";
                f17 = false;
            }

            if (selecteda18 == 1 && f18 == true) {
                selectSeat = selectSeat + "E2";
                f18 = false;
            }

            if (selecteda19 == 1 && f19 == true) {
                selectSeat = selectSeat + "E3";
                f19 = false;
            }

            if (selecteda20 == 1 && f20 == true) {
                selectSeat = selectSeat + "E4";
                f20 = false;
            }

            if (selecteda21 == 1 && f21 == true) {
                selectSeat = selectSeat + "F1";
                f21 = false;
            }

            if (selecteda22 == 1 && f22 == true) {
                selectSeat = selectSeat + "F2";
                f22 = false;
            }

            if (selecteda23 == 1 && f23 == true) {
                selectSeat = selectSeat + "F3";
                f23 = false;
            }

            if (selecteda24 == 1 && f24 == true) {
                selectSeat = selectSeat + "F4";
                f24 = false;
            }

            if (selecteda25 == 1 && f25 == true) {
                selectSeat = selectSeat + "G1";
                f25 = false;
            }

            if (selecteda26 == 1 && f26 == true) {
                selectSeat = selectSeat + "G2";
                f26 = false;
            }

            if (selecteda27 == 1 && f27 == true) {
                selectSeat = selectSeat + "G3";
                f27 = false;
            }

            if (selecteda28 == 1 && f28 == true) {
                selectSeat = selectSeat + "G4";
                f28 = false;
            }

            temp = temp - 1;
        }

        JOptionPane.showMessageDialog(null, selectSeat);

        /////// start
        try 
        {
            Connection con = MY_CNX.getConnection();
            Statement stmt = con.createStatement();
            String query = "select * from reserve";
            ResultSet rs = stmt.executeQuery(query);

            boolean check = false;
            String seatt;

            while (rs.next()) 
            {
                //JOptionPane.showMessageDialog(null,fromStr+" "+toStr+" "+dateStr+" "+timeStr);

                String f = rs.getString("fromLOC");
                String t = rs.getString("toLOC");
                String d = rs.getString("date");
                String ti = rs.getString("time");
                seatt = rs.getString("seat");

                //JOptionPane.showMessageDialog(null,f+" "+t+" "+d+" "+ti+" "+seatt);
                if (f.equals(fromStr)) 
                {
                    if (t.equals(toStr)) 
                    {
                        if (d.equals(dateStr)) 
                        {
                            if (ti.equals(timeStr)) 
                            {
                                check = true;

                                //String up = "UPDATE `reserve` SET `seat` = ? WHERE `fromLOC`=,`toLOC`=,`date`=,`time`=" + fromStr + toStr + dateStr + timeStr;
                                String up = "UPDATE `reserve` SET `seat` = ? WHERE `date` = ? AND `time` = ? AND `fromLOC` = ? AND `toLOC` = ?";

                                PreparedStatement pst;
                                
                                try 
                                {
                                    pst = (PreparedStatement) MY_CNX.getConnection().prepareStatement(up);
                                    pst.setString(1, (seatt+selectSeat));
                                    pst.setString(2, dateStr);
                                    pst.setString(3, timeStr);
                                    pst.setString(4, fromStr);
                                    pst.setString(5, toStr);
                                    
                                    pst.execute();
                                } 
                                
                                catch (SQLException ex) 
                                {
                                    Logger.getLogger(seatPlan.class.getName()).log(Level.SEVERE, null, ex);
                                }
                            }
                        }
                    }

                }

            }

            if (check == false) 
            {
                String in = "INSERT INTO `reserve`(`date`, `time`, `seat`, `fromLOC`, `toLOC`) VALUES (?,?,?,?,?)";

                //Connection conn = MY_CNX.getConnection();
                PreparedStatement pst;
                try 
                {
                    pst = (PreparedStatement) MY_CNX.getConnection().prepareStatement(in);

                    pst.setString(1, dateStr);
                    pst.setString(2, timeStr);
                    pst.setString(3, selectSeat);
                    pst.setString(4, fromStr);
                    pst.setString(5, toStr);
                    pst.execute();

                } 
                
                catch (SQLException ex) 
                {
                    Logger.getLogger(seatPlan.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

        } 
        
        catch (SQLException ex) 
        {
            JOptionPane.showMessageDialog(null, "Error");
        }

        //////  end
        //Dushto Code

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(seatPlan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(seatPlan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(seatPlan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(seatPlan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new seatPlan().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton A1;
    private javax.swing.JButton A10;
    private javax.swing.JButton A11;
    private javax.swing.JButton A12;
    private javax.swing.JButton A13;
    private javax.swing.JButton A14;
    private javax.swing.JButton A15;
    private javax.swing.JButton A16;
    private javax.swing.JButton A17;
    private javax.swing.JButton A18;
    private javax.swing.JButton A19;
    private javax.swing.JButton A2;
    private javax.swing.JButton A20;
    private javax.swing.JButton A21;
    private javax.swing.JButton A22;
    private javax.swing.JButton A23;
    private javax.swing.JButton A24;
    private javax.swing.JButton A25;
    private javax.swing.JButton A26;
    private javax.swing.JButton A27;
    private javax.swing.JButton A28;
    private javax.swing.JButton A3;
    private javax.swing.JButton A4;
    private javax.swing.JButton A5;
    private javax.swing.JButton A6;
    private javax.swing.JButton A7;
    private javax.swing.JButton A8;
    private javax.swing.JButton A9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JComboBox<String> passenger;
    public javax.swing.JComboBox<String> timeBUS;
    // End of variables declaration//GEN-END:variables
}
